### ISSUE TITLE
QA install page(s) metrics

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker.org#1278]
### Metrics checklist (Pre-flight) for Install Pages (desktop & iOS friendly error)

- [x] All the requirements from the kickoff checklist have been implemented (https://github.com/mozilla/webmaker.org/issues/1277)
- [x] Basic Goggle Analytics (GA) pageview tracking is present (#1258)
- [x] GA is using the correct account ID for the domain where this project is hosted (#1258)
- [x] GA pageview and event data is showing up in the realtime reports when tested in staging environment (#1258)
- [x] If conversion goals are being tracked, these have been configured in GA (#1261)
- [x] If required, custom GA events tracking is present (#1258)
- [ ] ~~If required, Optimizely standard tag is present~~
- [ ] ~~If required, Optimizely conversion goals have been instrumented~~
- [ ] If required, reporting is ready

**Comment by secretrobotron** [comment]
@adamlofting added some issue #'s above. Hoping to cover GA in #1258 mostly. How'd I do?

**Comment by secretrobotron** [comment]
@adamlofting new build is on staging, and has the analytics we discussed in it :). Check it out?

**Comment by adamlofting** [comment]
![screen shot 2015-02-26 at 09 15 57](https://cloud.githubusercontent.com/assets/1901816/6393446/1bbc53b6-bd98-11e4-923c-f72ede9b8c77.png)

Events are arriving on staging :boom:
